In [1]:
import pandas as pd

In [ ]:
df_raw = pd.read_csv("../data/raws/train(2).csv")

In [3]:
df_raw.head(10)

,dur,proto,service,state,spkts,dpkts,sbytes,dbytes,rate,sttl,...,ct_src_dport_ltm,ct_dst_sport_ltm,ct_dst_src_ltm,is_ftp_login,ct_ftp_cmd,ct_flw_http_mthd,ct_src_ltm,ct_srv_dst,is_sm_ips_ports,Label
0,0.022895,tcp,-,FIN,40,42,2542,23508,3537.890234,31,...,1,1,4,0,0,0,5,11,0,0
1,0.004540,udp,-,CON,4,4,568,304,1541.850183,31,...,1,1,3,0,0,0,4,7,0,0
2,0.761113,tcp,http,FIN,10,20,812,15532,38.102096,62,...,1,1,1,0,0,0,1,1,0,2
3,0.000003,emcon,-,INT,2,0,180,0,333333.321500,254,...,10,10,10,0,0,0,10,10,0,2
4,0.000008,udp,dns,INT,2,0,114,0,125000.000300,254,...,16,16,28,0,0,0,17,27,0,1
5,0.000008,udp,dns,INT,2,0,114,0,125000.000300,254,...,18,18,26,0,0,0,19,23,0,1
6,0.000009,udp,-,INT,2,0,104,0,111111.107200,254,...,3,3,6,0,0,0,3,6,0,3
7,0.697741,tcp,http,FIN,10,8,836,1326,24.364342,62,...,1,1,1,0,0,1,2,1,0,2
8,1.347953,tcp,http,FIN,28,134,1894,169716,119.440370,254,...,1,1,1,0,0,1,1,2,0,1
9,1.851700,tcp,-,FIN,10,8,946,354,9.180753,254,...,1,1,3,0,0,0,1,3,0,0

In [4]:
df_raw.shape

(180371, 43)

In [5]:
df_raw.columns

Index(['dur', 'proto', 'service', 'state', 'spkts', 'dpkts', 'sbytes',
       'dbytes', 'rate', 'sttl', 'dttl', 'sload', 'dload', 'sloss', 'dloss',
       'sinpkt', 'dinpkt', 'sjit', 'djit', 'swin', 'stcpb', 'dtcpb', 'dwin',
       'tcprtt', 'synack', 'ackdat', 'smean', 'dmean', 'trans_depth',
       'response_body_len', 'ct_srv_src', 'ct_state_ttl', 'ct_dst_ltm',
       'ct_src_dport_ltm', 'ct_dst_sport_ltm', 'ct_dst_src_ltm',
       'is_ftp_login', 'ct_ftp_cmd', 'ct_flw_http_mthd', 'ct_src_ltm',
       'ct_srv_dst', 'is_sm_ips_ports', 'Label'],
      dtype='str')

In [6]:
df_raw.info()

<class 'pandas.DataFrame'>
RangeIndex: 180371 entries, 0 to 180370
Data columns (total 43 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   dur                180371 non-null  float64
 1   proto              180371 non-null  str
 2   service            180371 non-null  str
 3   state              180371 non-null  str
 4   spkts              180371 non-null  int64
 5   dpkts              180371 non-null  int64
 6   sbytes             180371 non-null  int64
 7   dbytes             180371 non-null  int64
 8   rate               180371 non-null  float64
 9   sttl               180371 non-null  int64
 10  dttl               180371 non-null  int64
 11  sload              180371 non-null  float64
 12  dload              180371 non-null  float64
 13  sloss              180371 non-null  int64
 14  dloss              180371 non-null  int64
 15  sinpkt             180371 non-null  float64
 16  dinpkt             180371 non-null  float64
 17  sjit               180371 non-null  float64
 18  djit               180371 non-null  float64
 19  swin               180371 non-null  int64
 20  stcpb              180371 non-null  int64
 21  dtcpb              180371 non-null  int64
 22  dwin               180371 non-null  int64
 23  tcprtt             180371 non-null  float64
 24  synack             180371 non-null  float64
 25  ackdat             180371 non-null  float64
 26  smean              180371 non-null  int64
 27  dmean              180371 non-null  int64
 28  trans_depth        180371 non-null  int64
 29  response_body_len  180371 non-null  int64
 30  ct_srv_src         180371 non-null  int64
 31  ct_state_ttl       180371 non-null  int64
 32  ct_dst_ltm         180371 non-null  int64
 33  ct_src_dport_ltm   180371 non-null  int64
 34  ct_dst_sport_ltm   180371 non-null  int64
 35  ct_dst_src_ltm     180371 non-null  int64
 36  is_ftp_login       180371 non-null  int64
 37  ct_ftp_cmd         180371 non-null  int64
 38  ct_flw_http_mthd   180371 non-null  int64
 39  ct_src_ltm         180371 non-null  int64
 40  ct_srv_dst         180371 non-null  int64
 41  is_sm_ips_ports    180371 non-null  int64
 42  Label              180371 non-null  int64
dtypes: float64(11), int64(29), str(3)
memory usage: 59.2 MB

In [7]:
df_raw.describe()

,dur,spkts,dpkts,sbytes,dbytes,rate,sttl,dttl,sload,dload,...,ct_src_dport_ltm,ct_dst_sport_ltm,ct_dst_src_ltm,is_ftp_login,ct_ftp_cmd,ct_flw_http_mthd,ct_src_ltm,ct_srv_dst,is_sm_ips_ports,Label
count,180371.000000,180371.000000,180371.000000,1.803710e+05,1.803710e+05,1.803710e+05,180371.000000,180371.000000,1.803710e+05,1.803710e+05,...,180371.000000,180371.000000,180371.000000,180371.000000,180371.000000,180371.000000,180371.000000,180371.000000,180371.000000,180371.000000
mean,1.259370,19.760848,18.688065,8.512775e+03,1.463912e+04,9.108393e+04,179.965848,85.045412,7.053927e+07,6.581049e+05,...,5.251321,4.041587,8.323966,0.012696,0.012729,0.133248,6.811084,9.122353,0.014143,1.560256
std,6.031214,137.415753,117.460464,1.755446e+05,1.537443e+05,1.599175e+05,102.476930,112.877973,1.851258e+08,2.412133e+06,...,8.183103,5.843982,11.127000,0.115949,0.116327,0.681834,8.415118,10.880013,0.118081,1.718109
min,0.000000,1.000000,0.000000,2.400000e+01,0.000000e+00,0.000000e+00,0.000000,0.000000,0.000000e+00,0.000000e+00,...,1.000000,1.000000,1.000000,0.000000,0.000000,0.000000,1.000000,1.000000,0.000000,0.000000
25%,0.000008,2.000000,0.000000,1.140000e+02,0.000000e+00,3.078292e+01,62.000000,0.000000,1.230547e+04,0.000000e+00,...,1.000000,1.000000,1.000000,0.000000,0.000000,0.000000,2.000000,2.000000,0.000000,0.000000
50%,0.004342,4.000000,2.000000,5.280000e+02,1.780000e+02,2.952756e+03,254.000000,29.000000,7.394229e+05,1.777832e+03,...,1.000000,1.000000,3.000000,0.000000,0.000000,0.000000,3.000000,4.000000,0.000000,1.000000
75%,0.687237,12.000000,10.000000,1.356000e+03,1.070000e+03,1.250000e+05,254.000000,252.000000,8.000000e+07,2.225204e+04,...,4.000000,3.000000,8.000000,0.000000,0.000000,0.000000,8.000000,11.000000,0.000000,2.000000
max,59.999989,10646.000000,11018.000000,1.435577e+07,1.465753e+07,1.000000e+06,255.000000,254.000000,5.600000e+09,2.242273e+07,...,59.000000,46.000000,65.000000,4.000000,4.000000,30.000000,60.000000,62.000000,1.000000,9.000000

In [8]:
df_raw.isna().sum().sort_values(ascending=False)

dur                  0
proto                0
service              0
state                0
spkts                0
dpkts                0
sbytes               0
dbytes               0
rate                 0
sttl                 0
dttl                 0
sload                0
dload                0
sloss                0
dloss                0
sinpkt               0
dinpkt               0
sjit                 0
djit                 0
swin                 0
stcpb                0
dtcpb                0
dwin                 0
tcprtt               0
synack               0
ackdat               0
smean                0
dmean                0
trans_depth          0
response_body_len    0
ct_srv_src           0
ct_state_ttl         0
ct_dst_ltm           0
ct_src_dport_ltm     0
ct_dst_sport_ltm     0
ct_dst_src_ltm       0
is_ftp_login         0
ct_ftp_cmd           0
ct_flw_http_mthd     0
ct_src_ltm           0
ct_srv_dst           0
is_sm_ips_ports      0
Label                0
dtype: int64

In [9]:
df_raw = df_raw.dropna()

In [10]:
df_raw.isna().sum().sort_values(ascending=False)

dur                  0
proto                0
service              0
state                0
spkts                0
dpkts                0
sbytes               0
dbytes               0
rate                 0
sttl                 0
dttl                 0
sload                0
dload                0
sloss                0
dloss                0
sinpkt               0
dinpkt               0
sjit                 0
djit                 0
swin                 0
stcpb                0
dtcpb                0
dwin                 0
tcprtt               0
synack               0
ackdat               0
smean                0
dmean                0
trans_depth          0
response_body_len    0
ct_srv_src           0
ct_state_ttl         0
ct_dst_ltm           0
ct_src_dport_ltm     0
ct_dst_sport_ltm     0
ct_dst_src_ltm       0
is_ftp_login         0
ct_ftp_cmd           0
ct_flw_http_mthd     0
ct_src_ltm           0
ct_srv_dst           0
is_sm_ips_ports      0
Label                0
dtype: int64

In [11]:
df_raw.duplicated().sum()

np.int64(61522)

In [12]:
df_raw = df_raw.drop_duplicates()

In [13]:
df_raw.duplicated().sum()

np.int64(0)

In [14]:
df_raw["Label"].value_counts()

Label
0    60874
2    20302
3    15108
5     7220
1     6888
4     4380
6     1525
7     1406
8     1025
9      121
Name: count, dtype: int64

In [15]:
df_raw["proto"].value_counts()

proto
tcp           83085
udp           26500
unas           2909
ospf            804
arp             661
              ...
scps             30
nsfnet-igp       28
tlsp             26
igmp             23
icmp              8
Name: count, Length: 132, dtype: int64

In [16]:
df_raw["proto"].nunique()

132

In [17]:
df_raw["proto"].unique()

<StringArray>
[        'tcp',         'udp',       'emcon',     'pri-enc',        'unas',
         'prm',   'aes-sp3-d',     'trunk-1',         'cbt',         'pup',
 ...
         'snp',     'bbn-rcc',      'netblt',        'isis',         'dcn',
         'ddp',        'icmp', 'compaq-peer',        'sdrp',        'vrrp']
Length: 132, dtype: str

In [18]:
df_raw["service"].nunique()

13

In [19]:
df_raw["service"].unique()

<StringArray>
[       '-',     'http',      'dns',      'ftp',      'ssh',     'smtp',
 'ftp-data',     'pop3',     'dhcp',     'snmp',      'ssl',      'irc',
   'radius']
Length: 13, dtype: str

In [20]:
df_raw["state"].nunique()

9

In [21]:
df_raw["state"].unique()

<StringArray>
['FIN', 'CON', 'INT', 'REQ', 'RST', 'ECO', 'no', 'URN', 'ACC']
Length: 9, dtype: str