# Description des colonnes du dataset (Mobile Money Fraud)


## period
**Traduction :** Période / moment de la transaction  
**Explication :** Représente une dimension temporelle (temps simulé : heure, jour ou intervalle). Permet d’analyser les comportements dans le temps et de détecter des anomalies temporelles.

---

## operation
**Traduction :** Type d’opération  
**Explication :** Catégorie de la transaction (ex : transfert, retrait, dépôt, paiement). Certaines opérations peuvent être plus risquées que d’autres.

---

## amount
**Traduction :** Montant de la transaction  
**Explication :** Quantité d’argent transférée. C’est une variable clé pour détecter des comportements anormaux (montants très élevés ou inhabituels).

---

## origin_account
**Traduction :** Compte émetteur  
**Explication :** Identifiant du compte qui envoie l’argent. Permet d’analyser le comportement des utilisateurs et de détecter des comptes suspects.

---

## origin_balance_before
**Traduction :** Solde du compte émetteur avant transaction  
**Explication :** Montant disponible sur le compte avant l’opération. Utilisé pour vérifier la cohérence avec le montant transféré.

---

## origin_balance_after
**Traduction :** Solde du compte émetteur après transaction  
**Explication :** Montant restant après la transaction. Permet de calculer la variation du solde et détecter des incohérences.

---

## destination_account
**Traduction :** Compte receveur  
**Explication :** Identifiant du compte qui reçoit l’argent. Peut servir à détecter des réseaux de fraude ou des comptes impliqués dans plusieurs transactions suspectes.

---

## destination_balance_before
**Traduction :** Solde du compte receveur avant transaction  
**Explication :** Montant disponible sur le compte avant réception de l’argent.

---

## destination_balance_after
**Traduction :** Solde du compte receveur après transaction  
**Explication :** Montant après réception. Permet de vérifier la cohérence des flux financiers.

---

## fraud_flag
**Traduction :** Indicateur de fraude (variable cible)  
**Explication :** Variable à prédire :
- 0 = transaction normale  
- 1 = transaction frauduleuse  
Le modèle doit estimer la probabilité que cette valeur soit 1.

In [3]:
import pandas as pd

In [4]:
df_raw = pd.read_csv("../data/raws/dataset_files/train.csv")

In [5]:
df_raw.head(10)

,id,period,operation,amount,origin_account,origin_balance_before,origin_balance_after,destination_account,destination_balance_before,destination_balance_after,fraud_flag
0,dtf_0000001_ffa5beb5,0,op_05,636.75,acc_o_307358626ad66fed,87.00,-549.75,acc_d_7fac3b16af7d127b,630.88,1267.62,0
1,dtf_0000002_61992e82,0,op_05,636.12,acc_o_aeb690c57bf5d1de,76.93,76.93,acc_d_1d6120e8b117aa14,731.70,731.70,0
2,dtf_0000003_9a123b6d,0,op_05,681.00,acc_o_655c41913944d2b7,15943.74,15262.75,acc_d_ec2c21517a0ccb1a,758.83,1439.84,0
3,dtf_0000004_240f3dae,0,op_03,28175.40,acc_o_ba23a2b955a79a8b,-443.88,-28619.28,acc_d_a3dd8504815ec133,770924.84,799100.24,0
4,dtf_0000005_f18939e7,0,op_03,86429.15,acc_o_d05a23079bd066c1,-670.85,-87100.01,acc_d_0d4880267e62d5c4,91.13,86520.29,0
5,dtf_0000006_64d9bfcb,0,op_05,787.04,acc_o_6d8f4254f3f09623,25.81,25.81,acc_d_d2528fd81d284bd6,0.00,0.00,0
6,dtf_0000007_12c897cc,0,op_05,771.06,acc_o_6ad1fd4988e085ad,572637.44,571866.37,acc_d_256141e7a7c7947e,629.98,1401.04,0
7,dtf_0000008_2017ee18,0,op_05,758.83,acc_o_ed558e2b5b5af5f7,115.21,-643.62,acc_d_89927ea80de472e6,0.00,758.83,0
8,dtf_0000009_7388f093,0,op_03,96800.66,acc_o_9cc0fd44ac3f05d3,-658.41,-97459.06,acc_d_a0682983bf40c207,70.76,96871.41,1
9,dtf_0000010_c0647632,0,op_05,649.32,acc_o_d185654afcfec4e4,93.32,93.32,acc_d_4a34c3d6fd957589,706.31,706.31,0

In [6]:
df_raw.shape

(1290081, 11)

In [7]:
df_raw.info()

<class 'pandas.DataFrame'>
RangeIndex: 1290081 entries, 0 to 1290080
Data columns (total 11 columns):
 #   Column                      Non-Null Count    Dtype
---  ------                      --------------    -----
 0   id                          1290081 non-null  str
 1   period                      1290081 non-null  int64
 2   operation                   1290081 non-null  str
 3   amount                      1290081 non-null  float64
 4   origin_account              1290081 non-null  str
 5   origin_balance_before       1290081 non-null  float64
 6   origin_balance_after        1290081 non-null  float64
 7   destination_account         1290081 non-null  str
 8   destination_balance_before  1290081 non-null  float64
 9   destination_balance_after   1290081 non-null  float64
 10  fraud_flag                  1290081 non-null  int64
dtypes: float64(5), int64(2), str(4)
memory usage: 108.3 MB

In [8]:
df_raw.describe()

,period,amount,origin_balance_before,origin_balance_after,destination_balance_before,destination_balance_after,fraud_flag
count,1.290081e+06,1.290081e+06,1.290081e+06,1.290081e+06,1.290081e+06,1.290081e+06,1.290081e+06
mean,4.463454e+01,6.416038e+04,2.875629e+06,2.889497e+06,1.080057e+05,1.242356e+05,1.004138e-01
std,2.946460e+01,1.055554e+05,1.595036e+06,1.579518e+06,3.290812e+05,3.727577e+05,3.005511e-01
min,0.000000e+00,3.700000e-01,-2.358381e+05,-2.358381e+05,-2.339176e+05,-1.600515e+05,0.000000e+00
25%,1.800000e+01,7.173500e+02,1.766372e+06,1.803916e+06,8.662110e+03,2.327001e+04,0.000000e+00
50%,4.000000e+01,2.050616e+04,3.127788e+06,3.134523e+06,5.521809e+04,6.829976e+04,0.000000e+00
75%,6.800000e+01,8.752391e+04,4.031736e+06,4.030585e+06,1.274119e+05,1.356478e+05,0.000000e+00
max,1.050000e+02,2.526958e+06,1.443904e+07,1.443904e+07,1.401552e+07,1.422857e+07,1.000000e+00

In [9]:
df_raw.isna().sum()

id                            0
period                        0
operation                     0
amount                        0
origin_account                0
origin_balance_before         0
origin_balance_after          0
destination_account           0
destination_balance_before    0
destination_balance_after     0
fraud_flag                    0
dtype: int64

In [10]:
df_raw.duplicated().sum()

np.int64(0)

In [11]:
df_raw['fraud_flag'].value_counts()
df_raw['fraud_flag'].value_counts(normalize=True)

fraud_flag
0    0.899586
1    0.100414
Name: proportion, dtype: float64

In [12]:
df_raw.groupby('operation')['fraud_flag'].mean()

operation
op_01    0.000000
op_02    0.000000
op_03    0.311907
op_04    0.000000
op_05    0.000000
Name: fraud_flag, dtype: float64

In [13]:
df_raw['balance_diff_origin'] = df_raw['origin_balance_after'] - df_raw['origin_balance_before']
print((df_raw['balance_diff_origin'].abs() > 0.01).sum())
df_raw.groupby('fraud_flag')['balance_diff_origin'].describe()
df_raw.groupby('fraud_flag')['balance_diff_origin'].describe()

1247260

,count,mean,std,min,25%,50%,75%,max
fraud_flag,,,,,,,,
0,1160539.0,18451.927441,127736.742598,-2526957.67,-20120.70,-703.62,25856.13,723379.85
1,129542.0,-27198.408038,19110.854675,-447819.56,-28025.93,-22202.16,-20015.59,0.00

In [14]:
df_raw.to_csv("../data/processed/train_prepared.csv", index=False)